pr:
  autoCancel: "true"
  branches:
    include:
    - git
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml
stages:
- stage: TestSalesforceOrg
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/git'))
  jobs:
  - job: DeployTestOrg
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
          checkLatest: true
      - bash:
          npm install sfdx-cli --global
        displayName: Install Salesforce CLI
      - bash:
            sfdx config:set restDeploy=false --global
        displayName: Use SOAP API for Deployment
      - bash:
            sfdx force:auth:jwt:grant --clientid 3MVG9fe4g9fhX0E4eJChlLASqDfeYTNAvma5k5yPY1UNrsDkLrNByn8r_ZJV6dHsuoj9O1i.isCSC9Jr993tG --jwtkeyfile server.key --username devops2@gmail.com --instanceurl https://login.salesforce.com
        displayName: Authorize Salesforce DeployTestOrg Org
      - bash:
            sfdx force:source:deploy -p force-app -w 10 -u devops2@gmail.com
        displayName: Deploy source code to DeployTestOrg Org
